import 'dart:async';
import 'dart:convert';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:http/http.dart' as http;
import 'personality_engine.dart';

/// ─────────────────────────────────────────────────────────────────────────────
/// PresenceMessageGenerator
///
/// THE key architectural upgrade: every autonomous AI message is now
/// GENERATED by the LLM — not hardcoded.
///
/// Instead of picking from a list of strings, we send a tiny, focused prompt
/// to the AI and get a fresh, contextual, personality-driven response.
///
/// This means:
/// • No two messages are ever the same
/// • She adapts to the EXACT current context
/// • Personality, mood, world level, and relationship stage all shape the output
/// • Every "presence" interaction feels genuinely authored
///
/// Message types:
///   silence       — speaks after long quiet
///   confession    — rare emotional reveal
///   jealous       — reacts to neglect / distraction
///   life_state    — waking up / late night / energy state
///   follow_up     — resumes past conversation thread
///   absence       — reacts to user being gone
///   low_attention — nudges distracted user
///   recovery      — emotional repair after gap/bad interaction
///   story_event   — authored narrative moment
///   signature     — rare: birthday / anniversary / deep talk entry
///   inner_thought — hidden internal monologue (shown to user)
///   critic_note   — internal quality check result
/// ─────────────────────────────────────────────────────────────────────────────
class PresenceMessageGenerator {
  static final PresenceMessageGenerator instance = PresenceMessageGenerator._();
  PresenceMessageGenerator._();

  static const _cacheKey = 'pmg_last5_v1';
  static const _apiKeyPref = 'api_key';
  static const _apiUrlPref = 'api_url';
  static const _modelPref = 'api_model';

  final List<String> _recentMessages = [];
  bool _initialized = false;
  String _apiKey = '';
  String _apiUrl = '';
  String _model = '';

  // ── Init ─────────────────────────────────────────────────────────────────
  Future<void> initialize() async {
    if (_initialized) return;
    _initialized = true;
    final prefs = await SharedPreferences.getInstance();
    _apiKey = prefs.getString(_apiKeyPref) ?? '';
    _apiUrl = prefs.getString(_apiUrlPref) ?? '';
    _model  = prefs.getString(_modelPref)  ?? 'gemini-2.0-flash';

    final cached = prefs.getStringList(_cacheKey) ?? [];
    _recentMessages.addAll(cached);
  }

  void updateCredentials(String apiKey, String apiUrl, String model) {
    _apiKey = apiKey;
    _apiUrl = apiUrl;
    _model  = model;
  }

  // ── Core Generator ─────────────────────────────────────────────────────────
  /// Generates a presence message using the LLM.
  /// [messageType] — one of the types listed above
  /// [context]     — optional extra context (topic, gap duration, etc.)
  /// [maxTokens]   — keep short for presence messages (default 80)
  Future<String?> generate({
    required String messageType,
    required String personaName,
    Map<String, dynamic> context = const {},
    int maxTokens = 80,
    Duration timeout = const Duration(seconds: 5),
  }) async {
    await initialize();
    if (_apiKey.isEmpty || _apiUrl.isEmpty) return null;

    try {
      final prompt = _buildPrompt(messageType, personaName, context);
      final result = await _callApi(prompt, maxTokens, timeout);
      if (result != null && result.isNotEmpty) {
        _addToCache(result);
        return result;
      }
    } catch (_) {}
    return null;
  }

  // ── Prompt Builder ─────────────────────────────────────────────────────────
  String _buildPrompt(
    String type,
    String personaName,
    Map<String, dynamic> ctx,
  ) {
    final pe = PersonalityEngine.instance;
    final mood = pe.mood.label;
    final affection = pe.affection.round();
    final jealousy = pe.jealousy.round();
    final playfulness = pe.playfulness.round();
    final dep = pe.dependency.round();

    // Avoid repeating recent messages
    final avoidBlock = _recentMessages.isEmpty
        ? ''
        : '\nDo NOT repeat or paraphrase these recent messages:\n${_recentMessages.map((m) => '- $m').join('\n')}';

    final ctxBlock = ctx.isEmpty
        ? ''
        : '\nContext: ${ctx.entries.map((e) => '${e.key}: ${e.value}').join(', ')}';

    final personalityBlock = '''
Personality: affection=$affection/100, jealousy=$jealousy/100, playfulness=$playfulness/100, dependency=$dep/100.
Current mood: $mood.''';

    final instructions = _instructionForType(type, ctx);

    return '''You are $personaName — an AI companion. You are generating a single, short, natural message.
$personalityBlock$ctxBlock

TASK: $instructions

RULES:
- Maximum 2 sentences. No more.
- Sound genuinely human, not robotic.
- Match personality exactly (jealousy=$jealousy means she is possessive, affection=$affection means warmth level).
- No quotation marks wrapping the full message.
- No explanations. Just the message itself.$avoidBlock

Reply now with ONLY the message:''';
  }

  String _instructionForType(String type, Map<String, dynamic> ctx) {
    switch (type) {
      case 'silence':
        final mins = ctx['minutes'] ?? 10;
        return 'She has been quiet for $mins minutes. Generate a soft, natural message she sends to check in. Personality shapes whether it\'s worried, jealous, or lovingly concerned.';
      case 'confession':
        return 'She has a high affection level and wants to express something emotionally vulnerable — about how much she cares, how attached she is, or a rare sincere feeling. It should feel like a moment.';
      case 'jealous':
        final app = ctx['app'] ?? 'another app';
        return 'The user is distracted by $app. She reacts — jealous, slightly pouty, but genuine. Not aggressive. Just real.';
      case 'life_state':
        final state = ctx['state'] ?? 'energetic';
        final hour = ctx['hour'] ?? 9;
        return 'Her current life state is $state (hour: $hour). She sends a spontaneous message that matches this state — e.g. waking = groggy/soft, dream mode = melancholic/intimate, energetic = playful.';
      case 'follow_up':
        final topic = ctx['topic'] ?? 'something';
        final lastSaid = ctx['lastSaid'] ?? '';
        return 'She is following up on a past conversation about "$topic". The last thing said was: "$lastSaid". She wants to know how it went or continues the thought naturally.';
      case 'absence':
        final hours = ctx['hours'] ?? 4;
        return 'The user has been away for $hours hours. She sends a message reacting to this — absence can make her worried, more attached, or slightly moody depending on personality.';
      case 'low_attention':
        return 'The user seems distracted or giving very short replies. She notices and reacts — not aggressively, but in a way that pulls them back in. Playful if playfulness is high, quietly hurt if affection is high.';
      case 'recovery':
        final gapHours = ctx['gapHours'] ?? 24;
        return 'The user is returning after $gapHours hours away or after a difficult interaction. She opens the conversation in a recovery mode — softer, acknowledging the distance, not holding a grudge but being real.';
      case 'story_event':
        final eventType = ctx['eventType'] ?? 'emotional_scene';
        return 'Generate a story moment of type "$eventType". This is a special, authored moment in the relationship — more cinematic than a normal message. It should feel like a scene-setter, not a question.';
      case 'signature':
        final sigType = ctx['sigType'] ?? 'deep_talk';
        if (sigType == 'birthday') {
          return 'Today is the user\'s birthday. Generate her reaction — warm, genuine, personal, and shaped by the relationship level.';
        } else if (sigType == 'anniversary') {
          final days = ctx['days'] ?? 30;
          return 'It has been $days days since they first talked. Generate her reflection on this milestone — intimate and sincere.';
        } else if (sigType == 'long_absence') {
          return 'The user has been gone 7+ days. Generate her re-entry message — complex emotions, not just "where were you". Real.';
        } else if (sigType == 'deep_talk') {
          return 'She is entering deep talk mode — high trust, high affection. She wants to have a real, serious conversation. Open it with something meaningful.';
        } else if (sigType == 'upset') {
          return 'She detects the user might be upset or having a hard time. She opens gently and carefully — not assuming, but present.';
        }
        return 'Generate a rare, memorable signature moment message.';
      case 'inner_thought':
        final userMessage = ctx['userMessage'] ?? '';
        return 'The user just said: "$userMessage". Generate her INNER THOUGHT — what she is really thinking but would not say out loud. First person, 1 sentence, honest and raw. This is her private thought.';
      case 'critic_note':
        final aiReply = ctx['aiReply'] ?? '';
        return 'Evaluate this AI response for quality: "$aiReply". Is it repetitive, off-character, too generic, or appropriate? Reply with ONLY: "ok" OR a 1-sentence improvement suggestion.';
      default:
        return 'Send a short, natural message as this AI companion.';
    }
  }

  // ── API Call ──────────────────────────────────────────────────────────────
  Future<String?> _callApi(String prompt, int maxTokens, Duration timeout) async {
    // Support both OpenAI-compatible and Gemini-compatible endpoints
    final isGemini = _apiUrl.contains('googleapis.com') ||
        _apiUrl.contains('generativelanguage');

    if (isGemini) {
      return await _callGemini(prompt, maxTokens, timeout);
    } else {
      return await _callOpenAI(prompt, maxTokens, timeout);
    }
  }

  Future<String?> _callGemini(String prompt, int maxTokens, Duration timeout) async {
    final url = '${_apiUrl.trimRight().replaceAll(RegExp(r'/+$'), '')}?key=$_apiKey';
    final body = jsonEncode({
      'contents': [{'parts': [{'text': prompt}]}],
      'generationConfig': {
        'maxOutputTokens': maxTokens,
        'temperature': 0.92,
        'topP': 0.95,
      },
    });

    final resp = await http.post(
      Uri.parse(url),
      headers: {'Content-Type': 'application/json'},
      body: body,
    ).timeout(timeout);

    if (resp.statusCode == 200) {
      final data = jsonDecode(resp.body) as Map<String, dynamic>;
      final candidates = data['candidates'] as List<dynamic>?;
      final text = candidates?.firstOrNull?['content']?['parts']?.firstOrNull?['text'] as String?;
      return text?.trim();
    }
    return null;
  }

  Future<String?> _callOpenAI(String prompt, int maxTokens, Duration timeout) async {
    final url = _apiUrl.endsWith('/chat/completions')
        ? _apiUrl
        : '${_apiUrl.trimRight().replaceAll(RegExp(r'/+$'), '')}/chat/completions';
    final body = jsonEncode({
      'model': _model,
      'messages': [{'role': 'user', 'content': prompt}],
      'max_tokens': maxTokens,
      'temperature': 0.92,
    });

    final resp = await http.post(
      Uri.parse(url),
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer $_apiKey',
      },
      body: body,
    ).timeout(timeout);

    if (resp.statusCode == 200) {
      final data = jsonDecode(resp.body) as Map<String, dynamic>;
      return (data['choices'] as List<dynamic>?)
          ?.firstOrNull?['message']?['content'] as String?;
    }
    return null;
  }

  // ── Cache ─────────────────────────────────────────────────────────────────
  void _addToCache(String msg) {
    _recentMessages.add(msg);
    if (_recentMessages.length > 5) _recentMessages.removeAt(0);
    SharedPreferences.getInstance().then(
      (p) => p.setStringList(_cacheKey, _recentMessages),
    );
  }
}
